--- #YAML:1.0
name:               HTML-Calendar-Simple
version:            0.05
abstract:           A simple html calendar
author:
    - Stray Toaster <coder@straytoaster.co.uk>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI:           2.752
    Date::Simple:  1.03
    Test::More:    0.40
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
